---
# tasks file for compiling lustre from source


  # This is the repo as seen by the host running the build container
  - name: Enable codeready-builder-for-rhel-9-x86_64-rpms repository
    command: dnf config-manager --enable codeready-builder-for-rhel-9-x86_64-rpms

  - name: Install various dependencies
    ansible.builtin.dnf:
        name:
          - '@Development Tools'
          - 'mpitests-openmpi.x86_64'
          - 'openmpi-devel'
          - 'audit-libs-devel'
          - 'binutils-devel'
          - 'elfutils-devel'
          - 'kabi-dw'
          - 'ncurses-devel'
          - 'newt-devel'
          - 'numactl-devel'
          - 'openssl-devel'
          - 'pciutils-devel'
          - 'perl'
          - 'perl-devel'
          - 'xmlto'
          - 'xz-devel'
          - 'elfutils-libelf-devel'
          - 'libcap-devel'
          - 'libcap-ng-devel'
          - 'llvm-toolset'
          - 'kernel-rpm-macros'
          - 'keyutils-libs-devel'
          - 'keyutils'
          - 'libmount'
          - 'libmount-devel'
          - 'libnl3-devel'
          - 'libnl3'
          - 'kernel-abi-stablelists' # This package is valid for RHEL Minor Release lifetime: "With Red Hat Enterprise Linux 9, each minor release will have a unique stablelist that is valid throughout the minor release lifecycle. https://access.redhat.com/solutions/444773
          - 'kernel-headers-{{ target_kernel }}'
          - 'kernel-devel-{{ target_kernel }}'
          - 'kernel-core-{{ target_kernel }}'
          - 'libyaml'
          - 'libyaml-devel'
          - 'transfig'



  - name: "git checkout lustre sources"
    ansible.builtin.git:
        dest: "{{lustre_compilation_folder}}"
        force: true
        repo: "{{lustre_src_git_repo}}"
        version: "{{lustre_src_git_version}}"


  - name: Remove configure in order to run autogen.sh
    ansible.builtin.file:
      path: "{{lustre_compilation_folder}}/configure"
      state: absent

  - name: Remove Makefile in order to run configure
    ansible.builtin.file:
      path: "{{lustre_compilation_folder}}/Makefile"
      state: absent

  - name: autogen configure
    ansible.builtin.command:
        cmd: sh autogen.sh
        creates: configure
        chdir: "{{lustre_compilation_folder}}"


  - name: configure to create Makefile
    ansible.builtin.command:
        cmd: "./configure {{lustre_configure_parameters}}"
        chdir: "{{lustre_compilation_folder}}"
        creates: Makefile


  - name: make clean
    make:
        chdir: "{{lustre_compilation_folder}}"
        target: "clean"

  - name: set kernel version dependency
    lineinfile:
        path: "{{ lustre_compilation_folder }}/lustre.spec"
        insertafter: "^BuildRoot:.*"
        line: "{{ item }}"
    with_items:
        - "Requires: kernel == {{ target_kernel | regex_replace('\\.x86_64$', '') }}"
        - "# Added by ansible_role_lustre"
    when:
        - target_kernel is defined



  - name: make rpms
    make:
        chdir: "{{lustre_compilation_folder}}"
        target: "rpms"
