---
# tasks file for ansible_role_lustre


- name: Add lustre dnf repository
  ansible.builtin.yum_repository:
    name: "{{lustre_rpm_repo.name}}"
    description: "{{lustre_rpm_repo.description}}"
    baseurl: "{{lustre_rpm_repo.baseurl}}"
    gpgcheck: "{{lustre_rpm_repo.gpgcheck}}"
  tags: ['lustre']

- name: Install lustre client with dnf
  ansible.builtin.dnf:
    name: lustre-client
    state: latest
  tags: ['lustre']



# THE FOLLOWING MUST GO TO INFINIBAND ROLE
#- name: Add kernel module: ib_umad
#  community.general.modprobe:
#    name: ib_umad
#    state: present
#    persistent: present
#
#- name: Add kernel module: rdma_ucm
#  community.general.modprobe:
#    name: rdma_ucm
#    state: present
#    persistent: present
#
#- name: Add kernel module: lustre
#  community.general.modprobe:
#    name: lustre
#    state: present
#    persistent: present
#    params: 'options lnet networks="o2ib0({{ib_interface}})"
#options ko2iblnd peer_credits=16 credits=2048 ntx=2048'

