---
# tasks file for ansible_role_lustre


- name: Compile Lustre
  ansible.builtin.include: compile.yml
  when: true

- name: Install RPMs
  ansible.builtin.include: install_binary_rpms.yml
  when: false