---


- name: Add kernel module lustre
  community.general.modprobe:
    name: lustre
    state: present
    persistent: present
    params: 'options lnet networks="o2ib0({{ib_interface}})"'
  tags: ['notest']
  when:  (not 'chroot' in ansible_connection)  and (not 'docker' in ansible_connection ) and (not 'podman' in ansible_connection )

- name: Lustre modprobe.d confings
  template:
    src: lustre.conf.j2
    dest: /etc/modprobe.d/lustre.conf
    owner: root
    group: root
    mode: 0644
  when: ( lustre_lnet_networks is defined or lustre_modprobe_options is defined ) and ('chroot' in ansible_connection or 'docker' in ansible_connection or 'podman'  in ansible_connection  )



- name: Create the mount target directory if it does not exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ lustre_mounts }}"
  when: lustre_mounts is defined


- name: Add Lustre entry to /etc/fstab, make sure it is mounted
  ansible.posix.mount:
    fstype: lustre
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts | default(lustre_mount_opts) | join(',') }}"
    state: "{{ lustre_mount_state }}"
  loop: "{{ lustre_mounts }}"
  when: lustre_mounts is defined
  tags: ['notest']
