---
dependency:
  name: galaxy
#  options:
#    requirements-file: requirements.yml
driver:
  name: podman
platforms:
  - name: instance-rocky
    image: docker.io/rockylinux/rockylinux:9.2
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
